! zebra.conf - R5
! eth0 = lan5 | eth1 = link35 | eth2 = link45
hostname R5
password zebra
!
interface eth0
 description LAN5 - rede de acesso do R5
!
interface eth1
 description Link para R3
!
interface eth2
 description Link para R4
!
ip forwarding
!
line vty
!
