! ospfd.conf - R3
hostname R3
password zebra
!
interface eth1
 ip ospf network point-to-point
!
interface eth2
 ip ospf network point-to-point
!
interface eth3
 ip ospf network point-to-point
!
router ospf
 ospf router-id 3.3.3.3
 passive-interface eth0
 network 10.3.0.0/24 area 0
 network 10.0.13.0/29 area 0
 network 10.0.35.0/29 area 0
 network 10.0.23.0/29 area 0
!
line vty
!
