! zebra.conf - R3
! eth0 = lan3 | eth1 = link13 | eth2 = link35 | eth3 = link23
hostname R3
password zebra
!
interface eth0
 description LAN3 - rede de acesso do R3
!
interface eth1
 description Link para R1
!
interface eth2
 description Link para R5
!
interface eth3
 description Link para R2 (redundancia)
!
ip forwarding
!
line vty
!
