! zebra.conf - R2
! eth0 = lan2 | eth1 = link12 | eth2 = link24 | eth3 = link23
hostname R2
password zebra
!
interface eth0
 description LAN2 - rede de acesso do R2
!
interface eth1
 description Link para R1
!
interface eth2
 description Link para R4
!
interface eth3
 description Link para R3 (redundancia)
!
ip forwarding
!
line vty
!
