! zebra.conf - R4
! eth0 = lan4 | eth1 = link24 | eth2 = link45
hostname R4
password zebra
!
interface eth0
 description LAN4 - rede de acesso do R4
!
interface eth1
 description Link para R2
!
interface eth2
 description Link para R5
!
ip forwarding
!
line vty
!
