! zebra.conf - R1
! Interfaces conforme ORDEM declarada no docker-compose.yml para o servico r1:
!   eth0 = lan1   | eth1 = link12 | eth2 = link13
hostname R1
password zebra
!
interface eth0
 description LAN1 - rede de acesso do R1
!
interface eth1
 description Link para R2
!
interface eth2
 description Link para R3
!
ip forwarding
!
line vty
!
