! ospfd.conf - R5
hostname R5
password zebra
!
interface eth1
 ip ospf network point-to-point
!
interface eth2
 ip ospf network point-to-point
!
router ospf
 ospf router-id 5.5.5.5
 passive-interface eth0
 network 10.5.0.0/24 area 0
 network 10.0.35.0/29 area 0
 network 10.0.45.0/29 area 0
!
line vty
!
